POST http://localhost:8090/users
Content-Type: application/json

{
   "name": "Hampus Olsen",
   "email": "hampus@olsen.com",
   "password": "hampusolsen",
   "date-of-birth": "1988-12-20"
}

// WAI
###

POST http://localhost:8090/users/login
Content-Type: application/json

{
   "email": "hampus@olsen.com",
   "password": "hampusolsen"
}

// WAI
###

POST http://localhost:8090/users/token?refresh=true
Content-Type: application/json

{
   "refreshToken": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoiRW1tYSBTdGFubGV5IiwiZW1haWwiOiJlbW1hQHN0YW5sZXkuY29tIiwicGFzc3dvcmQiOiIkMmIkMTAkNXhxQ1JFZlJEa1RIalVBQWpNbG4wdVJ5MDc5LzdLeWsvWS5MQk9nMllxU2N3UUNWWmxJVXUiLCJkYXRlLW9mLWJpcnRoIjoiMTk5NS0wOC0wNiIsInJvb21zIjpbXSwiaWQiOiJhMjI1NWVkZi1hZWQ0LTQ0YjMtYTY5Mi0yY2FiMjUyNTljOWYiLCJpYXQiOjE1ODc3NjQ2MjcsImV4cCI6MTU4Nzg1MTAyN30.7os1-vDnnnlXcFBHrHV2d5yHFPZ_FGSZdqT9vV9kOGg"
}

// WAI
###

DELETE http://localhost:8090/users/21450686-f5fb-4b15-9a2e-242d745bc692
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoiSGFtcHVzIE9sc2VuIiwiZW1haWwiOiJoYW1wdXNAb2xzZW4uY29tIiwicGFzc3dvcmQiOiIkMmIkMTAkTnV0R21YWXp5SlFWcDhIeWVqUjROLjBXVDN5Z0NCeFo4Q0JBa0kvREp3VDhVNi5UVmlDQXkiLCJkYXRlLW9mLWJpcnRoIjoiMTk4OC0xMi0yMCIsInJvb21zIjpbXSwiaWQiOiIyMTQ1MDY4Ni1mNWZiLTRiMTUtOWEyZS0yNDJkNzQ1YmM2OTIiLCJpYXQiOjE1ODc3NjYyMTEsImV4cCI6MTU4Nzc2ODAxMX0.gi4DWCMnB0F1VcCnRmTEYy6wdAi-nynLJ4Rmicdvi68

{
   "password": "hampusolsen"
}